[project]
name = "irexp9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.0.8",
    "duckdb>=1.4.0",
    "google-genai>=1.38.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
]
